spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/virtual_baby
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        web: INFO
    com:
      virtual:
        virtualbaby: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: TRACE